# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Quality

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      working-directory: src


    - name: Test with pytest
      run: |
        pytest --junitxml=pytest-report.xml --cov=src --cov-config=.coveragerc --cov-report xml
    
    - name: fix code coverage paths
      run: |
        sed -i 's/\/home\/runner\/work\/pykube-switch\/pykube-switch\//\/github\/workspace\//g' coverage.xml
      

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
