# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Windows application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create package
      run: |
        pyinstaller --noconfirm --onedir --windowed --name "pykube-switch" --icon "./pykube.ico" ^
                    --add-data "./Icons;Icons/" --add-data "./Views;Views/" --add-data "./MaterialIcons;MaterialIcons/" ^
                    --hidden-import "PySide2.QtQuick" "./main.py"
      working-directory: src


    - uses: actions/upload-artifact@v2
      with:
        name: pykube-switch
        path: src/dist/pykube-switch
     
